### ISSUE TITLE
error downloading example project

### ISSUE THREAD

**Issue by mteillet** [mangroveorg/mangrove#1]
Hello, I am working with Python 3.7 on windows. I managed to pip install, however when I try to download the Example Project, I get the following error :

Example types downloaded
Traceback (most recent call last):
  File "C:\Users\MARTIN_FIXE\AppData\Roaming\Python\Python37\site-packages\mangrove\mgvUI.py", line 5018, in discover
    obj['code'] = obj['code'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

I managed to fix it by removing the ".decode('utf8')" as with python 3 all strings are unicode objects. Do I absolutely have to use Python 2.7 in order to test Mangrove ?

After that, the example types and graphs could be downloaded, but I then got the following error:

Traceback (most recent call last):
  File "C:\Users\MARTIN_FIXE\AppData\Roaming\Python\Python37\site-packages\mangrove\mgvUI.py", line 5048, in discover
    g.create()
  File "C:\Users\MARTIN_FIXE\AppData\Roaming\Python\Python37\site-packages\mangrove\mgvApi.py", line 927, in create
    node.create()
  File "C:\Users\MARTIN_FIXE\AppData\Roaming\Python\Python37\site-packages\mangrove\mgvApi.py", line 1497, in create
    v.create()
  File "C:\Users\MARTIN_FIXE\AppData\Roaming\Python\Python37\site-packages\mangrove\mgvApi.py", line 2147, in create
    self.setParameter(parameter, self.parameters[parameter])
  File "C:\Users\MARTIN_FIXE\AppData\Roaming\Python\Python37\site-packages\mangrove\mgvApi.py", line 2264, in setParameter
    original = self.node.type.getParameter(name, version_id=self.node.versionActive.typeForceVersion).default
AttributeError: 'NoneType' object has no attribute 'getParameter'

I was really interested in testing it out, maybe I am doing something wrong ? Thank you in advance

Martin

**Comment by mariot** [comment]
Hello!

Unfortunately, mangrove hasn't been updated to python 3 yet.
It would be awesome if it were :(

And PR are always welcome!
Thanks a lot
